---

- name: Install packages
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"

- name: Update to the latest version
  shell: pm2 updatePM2
  when: pm2_service_state != 'stopped'

- name: Looking up user home
  shell: >
    egrep "^{{ pm2_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Installing startup script
  command: "pm2 startup -u {{ pm2_user }} --hp {{ pm2_user_home.stdout }}"
